import Head from "next/head";
import styles from "../styles/Main.module.scss";
import { useThemeContext } from "@/context";
import ImageSlider from "../components/ImageSlider/ImageSlider";

export default function Home() {

    const { theme, setTheme } = useThemeContext();

    return (
        <div>
            <Head>
                <title>My blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href=""></link>
            </Head>
            <div className={`${styles.container} ${theme === 'dark' && styles.darkContainer}`} >
                <div className={styles.pageWrapper}>
                    <div className={styles.imageContainer}>
                        <ImageSlider />
                    </div>
                    <div className={styles.contentContainer}>
                        <h2 className={styles.title}>
                            I am a front end developer,
                            <br />
                            and also a cooker.
                        </h2>
                        <p className={styles.contentMidium}>
                            Now I live in Sydney, Australia.
                            <br />
                            Welcome to contact me.
                        </p>
                        <p className={styles.contentSmall}>
                            We can talk about coding,
                            <br />
                            or about cooking, life or reading...
                        </p>
                        <p className={styles.contentMini}>
                            By Fei
                        </p>

                    </div>

                </div>

            </div>

        </div>
    )
}